spring.application.name=consulta-reemplacamiento-ms
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss.SSS
spring.jackson.time-zone=America/Lima

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.profiles.active=${DEPLOY}
server.port=10110

server.servlet.context-path=/api

#spring.datasource.url=jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
secret.key=${SECRET_KEY}
