CREATE USER SCHEMA_ IDENTIFIED BY "PASSWORD";

GRANT CONNECT, RESOURCE TO SCHEMA_;

ALTER USER SCHEMA_ QUOTA UNLIMITED ON USERS;

CREATE TABLE SCHEMA_.PLACA (
    id_placa        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_placa    VARCHAR2(10) NOT NULL UNIQUE,
    marca           VARCHAR2(50),
    modelo          VARCHAR2(50),
    color           VARCHAR2(30),
    anio_fabricacion NUMBER(4),
    propietario_dni  VARCHAR2(15),
    estado          VARCHAR2(20) DEFAULT 'ACTIVO',
    fecha_registro  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones   VARCHAR2(500),

    CONSTRAINT check_estado CHECK (estado IN ('ACTIVO', 'INACTIVO', 'ALERTA', 'ROBADO'))
);

INSERT ALL
    INTO SCHEMA_.PLACA (numero_placa, marca, modelo, color, anio_fabricacion, propietario_dni, estado, observaciones)
    VALUES ('ABC123', 'Toyota', 'Corolla', 'Blanco', 2022, '12345678A', 'ACTIVO', 'Vehículo nuevo de flota')

    INTO SCHEMA_.PLACA (numero_placa, marca, modelo, color, anio_fabricacion, propietario_dni, estado, observaciones)
    VALUES ('XYZ987', 'Hyundai', 'Tucson', 'Gris Plata', 2020, '87654321B', 'ACTIVO', NULL)

    INTO SCHEMA_.PLACA (numero_placa, marca, modelo, color, anio_fabricacion, propietario_dni, estado, observaciones)
    VALUES ('DEF456', 'Nissan', 'Sentra', 'Negro', 2015, '45678912C', 'ROBADO', 'Reportado el 15 de marzo')

    INTO SCHEMA_.PLACA (numero_placa, marca, modelo, color, anio_fabricacion, propietario_dni, estado, observaciones)
    VALUES ('GHI789', 'Kia', 'Sportage', 'Rojo', 2018, '78912345D', 'INACTIVO', 'Baja por siniestro total')

    INTO SCHEMA_.PLACA (numero_placa, marca, modelo, color, anio_fabricacion, propietario_dni, estado, observaciones)
    VALUES ('JKL012', 'Ford', 'Ranger', 'Azul Metálico', 2023, '32165498E', 'ALERTA', 'Pendiente de verificación de motor')
SELECT 1 FROM DUAL;

-------------------------------------
CREATE SCHEMA EXTRANET
CREATE TABLE EXTRANET.PLACA (
                                id_placa        SERIAL PRIMARY KEY,
                                numero_placa    VARCHAR(10) NOT NULL UNIQUE,
                                marca           VARCHAR(50),
                                modelo          VARCHAR(50),
                                color           VARCHAR(30),
                                anio_fabricacion NUMERIC(4),
                                propietario_dni  VARCHAR(15),
                                estado          VARCHAR(20) DEFAULT 'ACTIVO',
                                fecha_registro  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                observaciones   VARCHAR(500),

                                CONSTRAINT check_estado CHECK (estado IN ('ACTIVO', 'INACTIVO', 'ALERTA', 'ROBADO'))
);

select * from EXTRANET.placa